version: 1
services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    routes:
      - src: /
        dest: /
